version: '3.8'

services:
  posts-service:
    container_name: ${POSTS_SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${POSTS_SERVICE_PORT_NUMBER}:80"
    depends_on:
      - ${MONGODB_CONTAINER_NAME}
    env_file:
      - .env
    networks:
      - posts-service-network

  posts-service-mongodb:
    container_name: ${MONGODB_CONTAINER_NAME}
    image: mongo
    ports:
      - "${MONGODB_PORT_NUMBER}:27017"
    volumes:
      - ./posts-service-volume:/data/db
    environment:
      - TZ=UTC
    user: mongodb
    env_file:
      - .env
    networks:
      - posts-service-network

networks:
  posts-service-network:
    driver: bridge

volumes:
  posts-service-volume:
