---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service-deployment
  namespace: posts-service
  labels:
    app: posts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
        - name: posts-service
          image: gigo123/posts-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: posts-service-config
          env:
            - name: MONGODB_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: mongodb_container_name
            - name: MONGODB_PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: mongodb_port_number
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: mongodb_password





