---
apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-service-config
  namespace: posts-service
data:
  DATABASE_NAME: PostsDB
  COLLECTION_NAME: Posts
  MAX_RETRY_ATTEMPTS: "10"
  RETRY_DELAY: "1"
