---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posts-service-mongodb-pvc
  namespace: posts-service
  labels:
    db: posts-service-mongodb
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
